services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: bm-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: benchmark
      CLICKHOUSE_USER: benchmark
      CLICKHOUSE_PASSWORD: benchmark
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144